### ISSUE TITLE
hello phd

### ISSUE THREAD

**Issue by szj-github** [andrew-saydjari/EqWS.jl#1]
hello . Do you have code with python?

**Comment by andrew-saydjari** [comment]
At this time, we do not have a direct python port. The code is fairly short so it would not be extremely difficulty to translate, but the performance (speed of the code) and validation would take significant time. Users primarily working in python can use https://pyjulia.readthedocs.io/en/stable/ (or https://github.com/JuliaPy/PyCall.jl ) to act as an easy interface between the two languages.

**Comment by szj-github** [comment]
> At this time, we do not have a direct python port. The code is fairly short so it would not be extremely difficulty to translate, but the performance (speed of the code) and validation would take significant time. Users primarily working in python can use https://pyjulia.readthedocs.io/en/stable/ (or https://github.com/JuliaPy/PyCall.jl ) to act as an easy interface between the two languages.

Thank you very much! already starred
